const defaults={name:'',role:'',email:'',phone:'',location:'',link:'',summary:'',jobTitle:'',company:'',start:'',end:'',achievements:'',degree:'',school:'',gradYear:'',skills:''};
const sample={name:'Maya Patel',role:'Senior Product Designer',email:'maya.patel@email.com',phone:'+1 415 555 0147',location:'San Francisco, CA',link:'linkedin.com/in/mayapatel',summary:'Product designer with 6+ years of experience turning complex workflows into intuitive products. Led research and design initiatives that improved activation by 24% and reduced support volume by 31%.',jobTitle:'Senior Product Designer',company:'Northstar Labs',start:'Jan 2022',end:'Present',achievements:'Led the end-to-end redesign of onboarding, increasing activation by 24% across 80,000 users\nBuilt and governed a design system adopted by 6 product teams, cutting delivery time by 30%\nRan 40+ user interviews and usability studies to guide product strategy',degree:'B.Des. Interaction Design',school:'California College of the Arts',gradYear:'2018',skills:'Product strategy, User research, Figma, Prototyping, Design systems, Usability testing, Analytics, Cross-functional leadership'};
let data={...defaults,...JSON.parse(localStorage.getItem('resumemint-data')||'{}')};
const panels=['basics','summary','experience','education','skills']; let current=0;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=s=>(s||'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
function syncInputs(){ $$('[data-field]').forEach(el=>el.value=data[el.dataset.field]||''); render(); }
function val(key,fallback){return esc(data[key]?.trim()||fallback)}
function render(){
  $('#pName').textContent=(data.name||'YOUR NAME').toUpperCase(); $('#pRole').textContent=(data.role||'PROFESSIONAL TITLE').toUpperCase();
  $('#pContact').textContent=[data.email||'email@example.com',data.phone,data.location||'City, Country',data.link||'linkedin.com/in/you'].filter(Boolean).join(' · ');
  $('#pSummary').textContent=data.summary||'Write a concise professional summary that shows your experience, strengths, and the value you bring.';
  $('#pJob').textContent=data.jobTitle||'Job Title'; $('#pCompany').textContent=data.company||'Company'; $('#pDates').textContent=[data.start||'2022',data.end||'Present'].join(' — ');
  const lines=(data.achievements||'Describe an achievement using an action verb and a measurable result.\nShow the scope of your work and the impact it created.').split('\n').filter(Boolean); $('#pAchievements').innerHTML=lines.map(x=>`<li>${esc(x)}</li>`).join('');
  $('#pDegree').textContent=data.degree||'Degree'; $('#pSchool').textContent=data.school||'University'; $('#pYear').textContent=data.gradYear||'2020'; $('#pSkills').textContent=data.skills||'Add your most relevant hard and soft skills.';
  localStorage.setItem('resumemint-data',JSON.stringify(data));
}
$$('[data-field]').forEach(el=>el.addEventListener('input',e=>{data[e.target.dataset.field]=e.target.value;render()}));
function showPanel(i){current=Math.max(0,Math.min(4,i)); $$('.panel').forEach((p,n)=>p.classList.toggle('active',n===current)); $$('.step').forEach((s,n)=>s.classList.toggle('active',n===current)); $('#stepLabel').textContent=`STEP ${current+1} OF 5`; $('#panelTitle').textContent=['Let’s start with the basics','Write a sharp professional summary','Show your measurable impact','Add your education','Finish with relevant skills'][current]; $('#prevBtn').disabled=current===0; $('#nextBtn').textContent=current===4?'Review resume ✓':'Continue →';}
$$('.step').forEach((s,i)=>s.addEventListener('click',()=>showPanel(i))); $('#prevBtn').onclick=()=>showPanel(current-1); $('#nextBtn').onclick=()=>current<4?showPanel(current+1):$('#checker').scrollIntoView();
$('#loadSample').onclick=()=>{data={...sample};syncInputs()}; $('#printBtn').onclick=()=>window.print();
$('#jobDescription').addEventListener('input',e=>$('#wordCount').textContent=`${e.target.value.trim()?e.target.value.trim().split(/\s+/).length:0} words`);
const stop=new Set('and the with for that this from your you are our will have has into about who what when where how job role work team using use a an to of in on at by as is be or we it they their them'.split(' '));
function getKeywords(text){const words=(text.toLowerCase().match(/[a-z][a-z+#.-]{2,}/g)||[]).filter(w=>!stop.has(w));const count={};words.forEach(w=>count[w]=(count[w]||0)+1);return Object.entries(count).sort((a,b)=>b[1]-a[1]).slice(0,18).map(x=>x[0]);}
function analyze(){const jd=$('#jobDescription').value.trim();const text=Object.values(data).join(' ').toLowerCase();const complete=['name','email','role','summary','jobTitle','company','achievements','education','skills'].reduce((n,k)=>n+(data[k]?1:0),0);const keywords=getKeywords(jd);const matched=keywords.filter(k=>text.includes(k));const structure=Math.min(100,complete*12);const keyword=keywords.length?Math.round(matched.length/keywords.length*100):40;const impact=Math.min(100,((data.achievements.match(/\d+|%|increased|reduced|improved|grew|saved|led|built/gi)||[]).length*14));const clarity=Math.min(100,40+(data.summary.length>=80?25:0)+(data.achievements.split('\n').filter(Boolean).length>=2?25:0)+(data.skills.split(',').length>=5?10:0));const score=Math.round(structure*.3+keyword*.35+impact*.2+clarity*.15);$('#scoreValue').textContent=score;$('#scoreLabel').textContent=score>=85?'Excellent match':score>=70?'Strong foundation':score>=50?'Needs a few improvements':'Build out your resume';$('#scoreSummary').textContent=score>=70?'Your resume is well aligned. Review the opportunities below.':'Complete missing sections and add relevant evidence.';const bars={Structure:structure,Keywords:keyword,Impact:impact,Clarity:clarity};$('#scoreBars').innerHTML=Object.entries(bars).map(([k,v])=>`<div class="score-row"><span>${k}</span><div class="bar"><i style="width:${v}%"></i></div><b>${v}</b></div>`).join('');const missing=keywords.filter(k=>!matched.includes(k)).slice(0,9);$('#keywordList').innerHTML=(missing.length?missing:['No major gaps found']).map(k=>`<span>${esc(k)}</span>`).join('');$('#results').classList.remove('hidden');$('#results').scrollIntoView({behavior:'smooth',block:'nearest'});}
$('#analyzeBtn').onclick=analyze; syncInputs(); showPanel(0);

const fileInput=$('#resumeFile'),dropZone=$('#dropZone'),auditReport=$('#auditReport');
['dragenter','dragover'].forEach(x=>dropZone.addEventListener(x,e=>{e.preventDefault();dropZone.classList.add('dragging')}));
['dragleave','drop'].forEach(x=>dropZone.addEventListener(x,e=>{e.preventDefault();dropZone.classList.remove('dragging')}));
dropZone.addEventListener('drop',e=>{if(e.dataTransfer.files[0])scanResumeFile(e.dataTransfer.files[0])});
fileInput.addEventListener('change',e=>{if(e.target.files[0])scanResumeFile(e.target.files[0])});
const issue=(level,title,detail)=>({level,title,detail});
function contentChecks(text,out){const clean=text.replace(/\s+/g,' ').trim(),words=(clean.toLowerCase().match(/[a-z][a-z+#.-]{2,}/g)||[]).filter(w=>!stop.has(w)),counts={};words.forEach(w=>counts[w]=(counts[w]||0)+1);const stuffed=Object.entries(counts).filter(([,n])=>n>=8&&n/Math.max(words.length,1)>.025).slice(0,5);out.push(clean.length<300?issue('warn','Very little readable text','The ATS may not be able to extract enough content.'):issue('pass','Readable content detected',`${words.length} words were available for analysis.`));out.push(stuffed.length?issue('danger','Possible keyword stuffing',`Unusually repeated: ${stuffed.map(([w,n])=>`${w} (${n}×)`).join(', ')}.`):issue('pass','No keyword stuffing pattern','Word repetition appears natural.'));if(!/@/.test(clean))out.push(issue('warn','Email address not detected','Keep contact information in the document body.'));if(!/\b(experience|employment|work history)\b/i.test(clean))out.push(issue('warn','Experience heading not detected','Use a standard heading such as “Experience”.'));}
async function scanDocx(buffer,out){if(!window.JSZip)throw new Error('DOCX scanner could not load. Check your connection and retry.');const zip=await JSZip.loadAsync(buffer),doc=await zip.file('word/document.xml')?.async('text');if(!doc)throw new Error('No readable DOCX body was found.');const xml=new DOMParser().parseFromString(doc,'application/xml'),text=[...xml.getElementsByTagNameNS('*','t')].map(n=>n.textContent).join(' '),hidden=(doc.match(/<w:vanish\b/g)||[]).length,white=(doc.match(/<w:color[^>]+w:val=["'](?:FFFFFF|ffffff|FFF|fff)["']/g)||[]).length,tiny=[...doc.matchAll(/<w:sz[^>]+w:val=["'](\d+)["']/g)].map(m=>+m[1]).filter(n=>n>0&&n<12).length;if(hidden)out.push(issue('danger','Hidden DOCX text detected',`${hidden} hidden text run${hidden>1?'s':''} found.`));if(white)out.push(issue('danger','White-on-white text detected',`${white} white font instruction${white>1?'s':''} found.`));if(tiny)out.push(issue('warn','Microscopic font detected',`${tiny} text run${tiny>1?'s':''} below 6 pt.`));if(!hidden&&!white)out.push(issue('pass','No hidden DOCX runs','No hidden or white-font instructions were found.'));contentChecks(text,out);}
function scanPdf(bytes,out){const raw=new TextDecoder('latin1').decode(bytes),invisible=(raw.match(/(?:^|\s)3\s+Tr\b/g)||[]).length,white=(raw.match(/(?:1(?:\.0+)?\s+){2}1(?:\.0+)?\s+(?:rg|RG)\b/g)||[]).length,transparent=(raw.match(/\/(?:ca|CA)\s+0(?:\.0+)?\b/g)||[]).length,tiny=[...raw.matchAll(/(?:^|\s)(\d*\.?\d+)\s+Tf\b/g)].map(m=>+m[1]).filter(n=>n>0&&n<6).length;if(invisible)out.push(issue('danger','Invisible PDF text detected',`${invisible} invisible rendering instruction${invisible>1?'s':''} found.`));if(white)out.push(issue('danger','White PDF text detected',`${white} white text instruction${white>1?'s':''} found.`));if(transparent)out.push(issue('danger','Zero-opacity content detected',`${transparent} transparency instruction${transparent>1?'s':''} found.`));if(tiny)out.push(issue('warn','Microscopic PDF text detected',`${tiny} font instruction${tiny>1?'s':''} below 6 pt.`));if(!invisible&&!white&&!transparent)out.push(issue('pass','No hidden PDF operators','No invisible, white-text, or zero-opacity operators were found.'));contentChecks([...raw.matchAll(/\(([^()]*)\)\s*Tj/g)].map(m=>m[1]).join(' '),out);}
function renderAudit(file,out){const danger=out.filter(x=>x.level==='danger').length,warn=out.filter(x=>x.level==='warn').length,risk=danger?'high':warn?'medium':'low',title=danger?'High rejection risk':warn?'Review recommended':'No hidden-text risk found';auditReport.innerHTML=`<div class="audit-result"><div class="audit-result-head"><div><small>${esc(file.name)} · ${(file.size/1024).toFixed(0)} KB</small><h3>${title}</h3><p>${danger?`${danger} serious issue${danger>1?'s':''} could look deceptive.`:warn?`${warn} item${warn>1?'s':''} should be reviewed.`:'The file passed the hidden-content checks.'}</p></div><span class="risk-badge risk-${risk}">${risk.toUpperCase()} RISK</span></div>${out.map(x=>`<div class="finding ${x.level}"><span>${x.level==='pass'?'✓':x.level==='danger'?'!':'?'}</span><div><b>${esc(x.title)}</b><small>${esc(x.detail)}</small></div></div>`).join('')}</div>`;}
async function scanResumeFile(file){if(file.size>10*1024*1024){auditReport.innerHTML='<div class="empty-report"><h3>File is too large</h3><p>Choose a resume smaller than 10 MB.</p></div>';return}auditReport.innerHTML='<div class="scan-progress"><div class="scan-ring"></div><h3>Inspecting your document…</h3><p>Looking for hidden content and rejection risks.</p></div>';try{const buffer=await file.arrayBuffer(),out=[];if(file.name.toLowerCase().endsWith('.docx'))await scanDocx(buffer,out);else if(file.name.toLowerCase().endsWith('.pdf'))scanPdf(new Uint8Array(buffer),out);else{contentChecks(new TextDecoder().decode(buffer),out);out.unshift(issue('pass','Plain-text file','TXT files cannot conceal formatted text.'));}renderAudit(file,out)}catch(err){auditReport.innerHTML=`<div class="empty-report"><h3>We couldn’t scan this file</h3><p>${esc(err.message||'Try another file.')}</p></div>`}}
