const defaults={name:'',role:'',email:'',phone:'',location:'',link:'',summary:'',jobTitle:'',company:'',start:'',end:'',achievements:'',degree:'',school:'',gradYear:'',skills:''};
const sample={name:'Maya Patel',role:'Senior Product Designer',email:'maya.patel@email.com',phone:'+1 415 555 0147',location:'San Francisco, CA',link:'linkedin.com/in/mayapatel',summary:'Product designer with 6+ years of experience turning complex workflows into intuitive products. Led research and design initiatives that improved activation by 24% and reduced support volume by 31%.',jobTitle:'Senior Product Designer',company:'Northstar Labs',start:'Jan 2022',end:'Present',achievements:'Led the end-to-end redesign of onboarding, increasing activation by 24% across 80,000 users\nBuilt and governed a design system adopted by 6 product teams, cutting delivery time by 30%\nRan 40+ user interviews and usability studies to guide product strategy',degree:'B.Des. Interaction Design',school:'California College of the Arts',gradYear:'2018',skills:'Product strategy, User research, Figma, Prototyping, Design systems, Usability testing, Analytics, Cross-functional leadership'};
let data={...defaults,...JSON.parse(localStorage.getItem('resumemint-data')||'{}')};
const panels=['basics','summary','experience','education','skills']; let current=0;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=s=>(s||'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
function syncInputs(){ $$('[data-field]').forEach(el=>el.value=data[el.dataset.field]||''); render(); }
function val(key,fallback){return esc(data[key]?.trim()||fallback)}
function render(){
  $('#pName').textContent=(data.name||'YOUR NAME').toUpperCase(); $('#pRole').textContent=(data.role||'PROFESSIONAL TITLE').toUpperCase();
  $('#pContact').textContent=[data.email||'email@example.com',data.phone,data.location||'City, Country',data.link||'linkedin.com/in/you'].filter(Boolean).join(' · ');
  $('#pSummary').textContent=data.summary||'Write a concise professional summary that shows your experience, strengths, and the value you bring.';
  $('#pJob').textContent=data.jobTitle||'Job Title'; $('#pCompany').textContent=data.company||'Company'; $('#pDates').textContent=[data.start||'2022',data.end||'Present'].join(' — ');
  const lines=(data.achievements||'Describe an achievement using an action verb and a measurable result.\nShow the scope of your work and the impact it created.').split('\n').filter(Boolean); $('#pAchievements').innerHTML=lines.map(x=>`<li>${esc(x)}</li>`).join('');
  $('#pDegree').textContent=data.degree||'Degree'; $('#pSchool').textContent=data.school||'University'; $('#pYear').textContent=data.gradYear||'2020'; $('#pSkills').textContent=data.skills||'Add your most relevant hard and soft skills.';
  localStorage.setItem('resumemint-data',JSON.stringify(data));
}
$$('[data-field]').forEach(el=>el.addEventListener('input',e=>{data[e.target.dataset.field]=e.target.value;render()}));
function showPanel(i){current=Math.max(0,Math.min(4,i)); $$('.panel').forEach((p,n)=>p.classList.toggle('active',n===current)); $$('.step').forEach((s,n)=>s.classList.toggle('active',n===current)); $('#stepLabel').textContent=`STEP ${current+1} OF 5`; $('#panelTitle').textContent=['Let’s start with the basics','Write a sharp professional summary','Show your measurable impact','Add your education','Finish with relevant skills'][current]; $('#prevBtn').disabled=current===0; $('#nextBtn').textContent=current===4?'Review resume ✓':'Continue →';}
$$('.step').forEach((s,i)=>s.addEventListener('click',()=>showPanel(i))); $('#prevBtn').onclick=()=>showPanel(current-1); $('#nextBtn').onclick=()=>current<4?showPanel(current+1):$('#checker').scrollIntoView();
$('#loadSample').onclick=()=>{data={...sample};syncInputs()}; $('#printBtn').onclick=()=>window.print();
$('#jobDescription').addEventListener('input',e=>$('#wordCount').textContent=`${e.target.value.trim()?e.target.value.trim().split(/\s+/).length:0} words`);
const stop=new Set('and the with for that this from your you are our will have has into about who what when where how job role work team using use a an to of in on at by as is be or we it they their them'.split(' '));
function getKeywords(text){const words=(text.toLowerCase().match(/[a-z][a-z+#.-]{2,}/g)||[]).filter(w=>!stop.has(w));const count={};words.forEach(w=>count[w]=(count[w]||0)+1);return Object.entries(count).sort((a,b)=>b[1]-a[1]).slice(0,18).map(x=>x[0]);}
function analyze(){const jd=$('#jobDescription').value.trim();const text=Object.values(data).join(' ').toLowerCase();const complete=['name','email','role','summary','jobTitle','company','achievements','education','skills'].reduce((n,k)=>n+(data[k]?1:0),0);const keywords=getKeywords(jd);const matched=keywords.filter(k=>text.includes(k));const structure=Math.min(100,complete*12);const keyword=keywords.length?Math.round(matched.length/keywords.length*100):40;const impact=Math.min(100,((data.achievements.match(/\d+|%|increased|reduced|improved|grew|saved|led|built/gi)||[]).length*14));const clarity=Math.min(100,40+(data.summary.length>=80?25:0)+(data.achievements.split('\n').filter(Boolean).length>=2?25:0)+(data.skills.split(',').length>=5?10:0));const score=Math.round(structure*.3+keyword*.35+impact*.2+clarity*.15);$('#scoreValue').textContent=score;$('#scoreLabel').textContent=score>=85?'Excellent match':score>=70?'Strong foundation':score>=50?'Needs a few improvements':'Build out your resume';$('#scoreSummary').textContent=score>=70?'Your resume is well aligned. Review the opportunities below.':'Complete missing sections and add relevant evidence.';const bars={Structure:structure,Keywords:keyword,Impact:impact,Clarity:clarity};$('#scoreBars').innerHTML=Object.entries(bars).map(([k,v])=>`<div class="score-row"><span>${k}</span><div class="bar"><i style="width:${v}%"></i></div><b>${v}</b></div>`).join('');const missing=keywords.filter(k=>!matched.includes(k)).slice(0,9);$('#keywordList').innerHTML=(missing.length?missing:['No major gaps found']).map(k=>`<span>${esc(k)}</span>`).join('');$('#results').classList.remove('hidden');$('#results').scrollIntoView({behavior:'smooth',block:'nearest'});}
$('#analyzeBtn').onclick=analyze; syncInputs(); showPanel(0);
